"""
app/services/ticket_service.py
────────────────────────────────
Business logic for ticket issuance, status transitions,
QR code retrieval, and bulk generation.

Each ticket gets a unique code:  TK + 10 uppercase hex chars
e.g. TK4A9BF21C30

The QR payload is generated by qr_service.generate_qr_code() and stored
as a base64-PNG string in Ticket.qr_data.  The raw PNG bytes are served
from the GET /tickets/{id}/qr.png endpoint.
"""

from __future__ import annotations

import base64
import secrets
import string
import uuid
from typing import List, Optional

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.event import Event
from app.models.ticket import Ticket
from app.models.visitor import Visitor
from app.schemas.ticket import BulkGenerateRequest, TicketCreate, TicketStatusUpdate
from app.services.qr_service import build_qr_payload, generate_qr_code


# ── Helpers ────────────────────────────────────────────────────────────────────

def _generate_ticket_code() -> str:
    """Return a unique ticket code: TK + 10 uppercase hex chars, no dashes."""
    return "TK" + secrets.token_hex(5).upper()


async def _get_or_404(db: AsyncSession, ticket_id: uuid.UUID) -> Ticket:
    result = await db.execute(select(Ticket).where(Ticket.id == ticket_id))
    ticket = result.scalar_one_or_none()
    if ticket is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket {ticket_id} not found",
        )
    return ticket


async def _visitor_exists(db: AsyncSession, visitor_id: uuid.UUID) -> Visitor:
    result = await db.execute(select(Visitor).where(Visitor.id == visitor_id))
    visitor = result.scalar_one_or_none()
    if visitor is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Visitor {visitor_id} not found",
        )
    return visitor


async def _event_exists(db: AsyncSession, event_id: uuid.UUID) -> None:
    result = await db.execute(select(Event).where(Event.id == event_id))
    if result.scalar_one_or_none() is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Event {event_id} not found",
        )


# ── CRUD ───────────────────────────────────────────────────────────────────────

async def get_all(
    db: AsyncSession,
    event_id: Optional[uuid.UUID],
    visitor_type_filter: Optional[str],
    ticket_status: Optional[str],
    pack: Optional[str],
    page: int,
    limit: int,
) -> List[Ticket]:
    """List tickets with optional filters."""
    from sqlalchemy import func

    query = select(Ticket)

    if event_id:
        query = query.where(Ticket.event_id == event_id)
    if ticket_status:
        query = query.where(Ticket.status == ticket_status)
    if pack:
        query = query.where(Ticket.pack == pack)

    # Filter by visitor type via join
    if visitor_type_filter:
        query = query.join(Visitor, Ticket.visitor_id == Visitor.id).where(
            Visitor.type == visitor_type_filter
        )

    query = (
        query
        .order_by(Ticket.created_at.desc())
        .offset((page - 1) * limit)
        .limit(limit)
    )
    result = await db.execute(query)
    return list(result.scalars().all())


async def get_by_id(db: AsyncSession, ticket_id: uuid.UUID) -> Ticket:
    return await _get_or_404(db, ticket_id)


async def create(db: AsyncSession, data: TicketCreate) -> Ticket:
    """Create a single ticket and generate its QR code."""
    visitor = await _visitor_exists(db, data.visitor_id)
    await _event_exists(db, data.event_id)

    # Verify visitor belongs to the given event
    if str(visitor.event_id) != str(data.event_id):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Visitor does not belong to the specified event",
        )

    code      = _generate_ticket_code()
    qr_bytes  = generate_qr_code(code, str(data.event_id), str(data.visitor_id))
    qr_b64    = base64.b64encode(qr_bytes).decode()

    ticket = Ticket(
        code=code,
        pack=data.pack,
        status=data.status,
        qr_data=qr_b64,
        visitor_id=data.visitor_id,
        event_id=data.event_id,
    )
    db.add(ticket)
    await db.flush()
    await db.refresh(ticket)
    return ticket


async def update_status(
    db: AsyncSession,
    ticket_id: uuid.UUID,
    data: TicketStatusUpdate,
) -> Ticket:
    """Transition a ticket to a new status."""
    ticket = await _get_or_404(db, ticket_id)
    ticket.status = data.status
    await db.flush()
    await db.refresh(ticket)
    return ticket


async def get_qr_png(db: AsyncSession, ticket_id: uuid.UUID) -> bytes:
    """
    Return the QR code PNG bytes for a ticket.

    Regenerates the QR on-the-fly if qr_data is missing (e.g., legacy rows).
    """
    ticket = await _get_or_404(db, ticket_id)

    if ticket.qr_data:
        # qr_data stored as base64 PNG
        return base64.b64decode(ticket.qr_data)

    # Fallback: regenerate
    qr_bytes = generate_qr_code(
        ticket.code, str(ticket.event_id), str(ticket.visitor_id)
    )
    # Persist so we don't regenerate next time
    ticket.qr_data = base64.b64encode(qr_bytes).decode()
    await db.flush()
    return qr_bytes


# ── Bulk generation ────────────────────────────────────────────────────────────

async def bulk_generate(
    db: AsyncSession,
    data: BulkGenerateRequest,
) -> dict:
    """
    Generate one ticket per visitor in visitor_ids.

    Visitors that already have a ticket for this event are skipped.
    Returns {generated, skipped, ticket_ids}.
    """
    await _event_exists(db, data.event_id)

    # Find visitors that already have tickets for this event
    existing_result = await db.execute(
        select(Ticket.visitor_id).where(
            Ticket.event_id == data.event_id,
            Ticket.visitor_id.in_([str(vid) for vid in data.visitor_ids]),
        )
    )
    already_ticketed: set[str] = {
        str(row[0]) for row in existing_result.fetchall()
    }

    generated_ids: List[uuid.UUID] = []
    skipped = 0

    for visitor_id in data.visitor_ids:
        if str(visitor_id) in already_ticketed:
            skipped += 1
            continue

        # Verify visitor exists and belongs to this event
        v_result = await db.execute(
            select(Visitor).where(
                Visitor.id == visitor_id,
                Visitor.event_id == data.event_id,
            )
        )
        visitor = v_result.scalar_one_or_none()
        if visitor is None:
            skipped += 1
            continue

        code      = _generate_ticket_code()
        ticket_id = uuid.uuid4()                  # generate UUID now — not deferred
        qr_bytes  = generate_qr_code(code, str(data.event_id), str(visitor_id))
        qr_b64    = base64.b64encode(qr_bytes).decode()

        ticket = Ticket(
            id=ticket_id,                          # set explicitly so it's available immediately
            code=code,
            pack=data.pack,
            status="pending",
            qr_data=qr_b64,
            visitor_id=visitor_id,
            event_id=data.event_id,
        )
        db.add(ticket)
        generated_ids.append(ticket_id)

    if generated_ids:
        await db.flush()

    return {
        "generated":  len(generated_ids),
        "skipped":    skipped,
        "ticket_ids": generated_ids,
    }
