/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisiteursRouteImport } from './routes/visiteurs'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LieuxRouteImport } from './routes/lieux'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as FloorPlanRouteImport } from './routes/floor-plan'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExposantsRouteImport } from './routes/exposants'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AutomatisationRouteImport } from './routes/automatisation'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as AccessManagementRouteImport } from './routes/access-management'
import { Route as IndexRouteImport } from './routes/index'

const VisiteursRoute = VisiteursRouteImport.update({
  id: '/visiteurs',
  path: '/visiteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxRoute = LieuxRouteImport.update({
  id: '/lieux',
  path: '/lieux',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanRoute = FloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposantsRoute = ExposantsRouteImport.update({
  id: '/exposants',
  path: '/exposants',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatisationRoute = AutomatisationRouteImport.update({
  id: '/automatisation',
  path: '/automatisation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessManagementRoute = AccessManagementRouteImport.update({
  id: '/access-management',
  path: '/access-management',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/badges': typeof BadgesRoute
  '/evenements': typeof EvenementsRoute
  '/exposants': typeof ExposantsRoute
  '/finance': typeof FinanceRoute
  '/floor-plan': typeof FloorPlanRoute
  '/landing-page': typeof LandingPageRoute
  '/leads': typeof LeadsRoute
  '/lieux': typeof LieuxRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/parametres': typeof ParametresRoute
  '/programme': typeof ProgrammeRoute
  '/rapports': typeof RapportsRoute
  '/scanner': typeof ScannerRoute
  '/visiteurs': typeof VisiteursRoute
  '/traffic': typeof TrafficRoute
  '/access-management': typeof AccessManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/badges': typeof BadgesRoute
  '/evenements': typeof EvenementsRoute
  '/exposants': typeof ExposantsRoute
  '/finance': typeof FinanceRoute
  '/floor-plan': typeof FloorPlanRoute
  '/landing-page': typeof LandingPageRoute
  '/leads': typeof LeadsRoute
  '/lieux': typeof LieuxRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/parametres': typeof ParametresRoute
  '/programme': typeof ProgrammeRoute
  '/rapports': typeof RapportsRoute
  '/scanner': typeof ScannerRoute
  '/visiteurs': typeof VisiteursRoute
  '/traffic': typeof TrafficRoute
  '/access-management': typeof AccessManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/badges': typeof BadgesRoute
  '/evenements': typeof EvenementsRoute
  '/exposants': typeof ExposantsRoute
  '/finance': typeof FinanceRoute
  '/floor-plan': typeof FloorPlanRoute
  '/landing-page': typeof LandingPageRoute
  '/leads': typeof LeadsRoute
  '/lieux': typeof LieuxRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/parametres': typeof ParametresRoute
  '/programme': typeof ProgrammeRoute
  '/rapports': typeof RapportsRoute
  '/scanner': typeof ScannerRoute
  '/visiteurs': typeof VisiteursRoute
  '/traffic': typeof TrafficRoute
  '/access-management': typeof AccessManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automatisation'
    | '/badges'
    | '/evenements'
    | '/exposants'
    | '/finance'
    | '/floor-plan'
    | '/landing-page'
    | '/leads'
    | '/lieux'
    | '/login'
    | '/marketing'
    | '/parametres'
    | '/programme'
    | '/rapports'
    | '/scanner'
    | '/visiteurs'
    | '/traffic'
    | '/access-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automatisation'
    | '/badges'
    | '/evenements'
    | '/exposants'
    | '/finance'
    | '/floor-plan'
    | '/landing-page'
    | '/leads'
    | '/lieux'
    | '/login'
    | '/marketing'
    | '/parametres'
    | '/programme'
    | '/rapports'
    | '/scanner'
    | '/visiteurs'
    | '/traffic'
    | '/access-management'
  id:
    | '__root__'
    | '/'
    | '/automatisation'
    | '/badges'
    | '/evenements'
    | '/exposants'
    | '/finance'
    | '/floor-plan'
    | '/landing-page'
    | '/leads'
    | '/lieux'
    | '/login'
    | '/marketing'
    | '/parametres'
    | '/programme'
    | '/rapports'
    | '/scanner'
    | '/visiteurs'
    | '/traffic'
    | '/access-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomatisationRoute: typeof AutomatisationRoute
  BadgesRoute: typeof BadgesRoute
  EvenementsRoute: typeof EvenementsRoute
  ExposantsRoute: typeof ExposantsRoute
  FinanceRoute: typeof FinanceRoute
  FloorPlanRoute: typeof FloorPlanRoute
  LandingPageRoute: typeof LandingPageRoute
  LeadsRoute: typeof LeadsRoute
  LieuxRoute: typeof LieuxRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  ParametresRoute: typeof ParametresRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RapportsRoute: typeof RapportsRoute
  ScannerRoute: typeof ScannerRoute
  VisiteursRoute: typeof VisiteursRoute
  TrafficRoute: typeof TrafficRoute
  AccessManagementRoute: typeof AccessManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visiteurs': {
      id: '/visiteurs'
      path: '/visiteurs'
      fullPath: '/visiteurs'
      preLoaderRoute: typeof VisiteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux': {
      id: '/lieux'
      path: '/lieux'
      fullPath: '/lieux'
      preLoaderRoute: typeof LieuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan': {
      id: '/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof FloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposants': {
      id: '/exposants'
      path: '/exposants'
      fullPath: '/exposants'
      preLoaderRoute: typeof ExposantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatisation': {
      id: '/automatisation'
      path: '/automatisation'
      fullPath: '/automatisation'
      preLoaderRoute: typeof AutomatisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-management': {
      id: '/access-management'
      path: '/access-management'
      fullPath: '/access-management'
      preLoaderRoute: typeof AccessManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomatisationRoute: AutomatisationRoute,
  BadgesRoute: BadgesRoute,
  EvenementsRoute: EvenementsRoute,
  ExposantsRoute: ExposantsRoute,
  FinanceRoute: FinanceRoute,
  FloorPlanRoute: FloorPlanRoute,
  LandingPageRoute: LandingPageRoute,
  LeadsRoute: LeadsRoute,
  LieuxRoute: LieuxRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  ParametresRoute: ParametresRoute,
  ProgrammeRoute: ProgrammeRoute,
  RapportsRoute: RapportsRoute,
  ScannerRoute: ScannerRoute,
  VisiteursRoute: VisiteursRoute,
  TrafficRoute: TrafficRoute,
  AccessManagementRoute: AccessManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
