"""
app/routers/exhibitors.py
──────────────────────────
FastAPI router — Exhibitor CRUD, status management, leads, and PDF offer.

Endpoints:
  GET    /api/v1/exhibitors                       list (filter: status/sector/event_id)
  POST   /api/v1/exhibitors                       register exhibitor
  GET    /api/v1/exhibitors/{id}                  detail with booth + payment info
  PUT    /api/v1/exhibitors/{id}                  update exhibitor
  PUT    /api/v1/exhibitors/{id}/status            validate / refuse exhibitor
  GET    /api/v1/exhibitors/{id}/leads             leads generated by exhibitor
  GET    /api/v1/exhibitors/{id}/offer.pdf         download PDF commercial offer
"""

from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_organizer_or_admin, get_current_user
from app.schemas.exhibitor import (
    ExhibitorCreate,
    ExhibitorResponse,
    ExhibitorStatusUpdate,
    ExhibitorUpdate,
    LeadSummaryResponse,
)
from app.services import exhibitor_service

router = APIRouter(prefix="/api/v1/exhibitors", tags=["Exhibitors"])


# ── GET /api/v1/exhibitors ─────────────────────────────────────────────────────

@router.get(
    "",
    response_model=list[ExhibitorResponse],
    summary="List exhibitors with optional filters",
)
async def list_exhibitors(
    status: Optional[str] = Query(
        None,
        description="pending | validated | refused | waiting_payment",
    ),
    sector: Optional[str] = Query(None, description="Filter by industry sector"),
    event_id: Optional[UUID] = Query(None, description="Filter by event UUID"),
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    return await exhibitor_service.get_all(db, status, sector, event_id, page, limit)


# ── POST /api/v1/exhibitors ────────────────────────────────────────────────────

@router.post(
    "",
    response_model=ExhibitorResponse,
    status_code=201,
    summary="Register a new exhibitor",
)
async def register_exhibitor(
    data: ExhibitorCreate,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Any authenticated user may register an exhibitor.
    Initial status is always **pending** until validated by an organiser.
    """
    return await exhibitor_service.create(db, data, current_user)


# ── GET /api/v1/exhibitors/{id} ────────────────────────────────────────────────

@router.get(
    "/{exhibitor_id}",
    response_model=ExhibitorResponse,
    summary="Get exhibitor detail (with booth and payment info)",
)
async def get_exhibitor(
    exhibitor_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    return await exhibitor_service.get_by_id(db, exhibitor_id)


# ── PUT /api/v1/exhibitors/{id} ────────────────────────────────────────────────

@router.put(
    "/{exhibitor_id}",
    response_model=ExhibitorResponse,
    summary="Update exhibitor information",
)
async def update_exhibitor(
    exhibitor_id: UUID,
    data: ExhibitorUpdate,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    return await exhibitor_service.update(db, exhibitor_id, data)


# ── PUT /api/v1/exhibitors/{id}/status ────────────────────────────────────────

@router.put(
    "/{exhibitor_id}/status",
    response_model=ExhibitorResponse,
    summary="Update exhibitor validation status (organizer / admin)",
)
async def update_exhibitor_status(
    exhibitor_id: UUID,
    data: ExhibitorStatusUpdate,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_organizer_or_admin),
):
    """
    Transition the exhibitor status:
    **pending → validated | refused | waiting_payment**

    Only a validated exhibitor may reserve a booth.
    """
    return await exhibitor_service.update_status(db, exhibitor_id, data)


# ── GET /api/v1/exhibitors/{id}/leads ─────────────────────────────────────────

@router.get(
    "/{exhibitor_id}/leads",
    response_model=list[LeadSummaryResponse],
    summary="List leads generated by this exhibitor",
)
async def get_exhibitor_leads(
    exhibitor_id: UUID,
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    return await exhibitor_service.get_leads(db, exhibitor_id, page, limit)


# ── GET /api/v1/exhibitors/{id}/offer.pdf ─────────────────────────────────────

@router.get(
    "/{exhibitor_id}/offer.pdf",
    summary="Download PDF commercial offer for this exhibitor",
    response_class=Response,
    responses={
        200: {
            "content": {"application/pdf": {}},
            "description": "PDF document — Commercial Offer",
        }
    },
)
async def get_offer_pdf(
    exhibitor_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Generate and stream a ReportLab PDF containing:
    - AI EVENT OS branding + event info
    - Exhibitor company details and package
    - Assigned booth: number, zone, size, price HT + 20% VAT = TTC (MAD)
    - Included services per package tier
    - Payment terms, bank details (MAD), and signature block
    """
    pdf_bytes = await exhibitor_service.generate_offer_pdf(db, exhibitor_id)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f"attachment; filename=\"offer-{str(exhibitor_id)[:8]}.pdf\""
            ),
            "Content-Length": str(len(pdf_bytes)),
        },
    )
